#########################
# DO NOT EDIT THIS FILE #
#########################
import app
import singleton
import game_server
import signalrcore.hub_connection_builder

class LHAPIService(metaclass=singleton.Singleton):
    def __init__(self):
        self.__game_server = game_server.GameServer()

        self.__hub = hub_connection_builder.HubConnectionBuilder() \
            .with_url(app.Settings().lhapi_url + "/teamshub") \
            .with_automatic_reconnect({
                "type": "raw",
                "keep_alive_interval": 10,
                "reconnect_interval": 5,
            }) \
            .build()
        self.__hub.on_open(self.__on_open)
        self.__hub.on_close(self.__on_close)
        self.__hub.on("AssignTeamId", self.__on_assign_team_id)

    def start(self):
        self.__hub.start()

    def join(self):
        self.__hub._thread.join()

    def __on_open(self):
        print("lhapi: connection opened and handshake received")

    def __on_close(self):
        print("lhapi: connection closed")

    def __on_assign_team_id(self, team_id):
        self.__game_server.set_team_id(team_id)
