#########################
# DO NOT EDIT THIS FILE #
#########################
from helper.app import Settings
from helper.singleton import Singleton
from helper.game_server import GameServerService
from signalrcore.hub_connection_builder import HubConnectionBuilder

class LHAPIService(metaclass=Singleton):
    def __init__(self):
        self.__game_server = GameServerService()

        self.__hub = HubConnectionBuilder() \
            .with_url(Settings().lhapi_url + "/teamshub") \
            .with_automatic_reconnect({
                "type": "raw",
                "keep_alive_interval": 10,
                "reconnect_interval": 5,
            }) \
            .build()
        self.__hub.on_open(self.__on_open)
        self.__hub.on_close(self.__on_close)
        self.__hub.on("AssignTeamId", self.__on_assign_team_id)

    def start(self):
        self.__hub.start()

    def join(self):
        self.__hub.hub._thread.join()

    def __on_open(self):
        print("lhapi: connection opened and handshake received")

    def __on_close(self):
        print("lhapi: connection closed")

    def __on_assign_team_id(self, team_id):
        self.__set_team_id(team_id)
