#########################
# DO NOT EDIT THIS FILE #
#########################
import bot
import helper.game_server
import helper.lhapi

if __name__ == '__main__':
    bot = bot.Bot()

    game_server.GameServerService().set_bot(bot)
    game_server.GameServerService().start()
    lhapi.LHAPIService().start()

    game_server.GameServerService().join()
    lhapi.LHAPIService().join()
